name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'
        
    - name: Install Dependencies
      run: npm install
      
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.14
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "todo-list-anelisiw3"
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        procfile: "web: node server.js"
      env:
        HD_MONGODB_URI: ${{ secrets.MONGODB_URI }}
        
    - name: Health Check
      run: |
        sleep 30
        curl https://todo-list-anelisiw3.herokuapp.com/health || exit 1
